# Generated by Django 5.1.5 on 2025-01-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgmt_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Items',
            new_name='Order_Item',
        ),
    ]
